Shop/ViewModels/HomeViewModel.cs
using Shop.Date.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class HomeViewModel
    {
        public IEnumerable<Knife> favKnives { get; set; }
    }
}

Shop/ViewModels/KnifeListViewModel.cs
using Shop.Date.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class KnifeListViewModel
    {
        public IEnumerable<Knife> GetKnives { get; set; }
        public string currCategory { get; set; }

    }
}

Shop/ViewModels/ShopCartViewModel.cs
using Shop.Date.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.ViewModels
{
    public class ShopCartViewModel
    {
        public ShopCart shopCart { get; set; } 
    }
}

Shop/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Date.Interfaces;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class HomeController : Controller
    {
        private readonly IAllKnives _knifeRep;
        

        public HomeController(IAllKnives knifeRep)
        {
            _knifeRep = knifeRep; 
        }

        public ViewResult Index()
        {
            var homeKnives = new HomeViewModel
            {
                favKnives = _knifeRep.getFavKnives
            };
            return View(homeKnives);
        }

    }
}

Shop/Controllers/KnivesController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Date.Interfaces;
using Shop.Date.Models;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace Shop.Controllers
{
    public class KnivesController : Controller
    {
        private readonly IAllKnives _allKnives;
        private readonly IKnifesCategory _allknifesCategory;

        public KnivesController(IAllKnives iAllknives, IKnifesCategory iKnifesCategory)
        {
            _allKnives = iAllknives;
            _allknifesCategory = iKnifesCategory;
        }
        [Route("Knive/List")]
        [Route("Knive/List/{category}")]
        public ViewResult List(string category)
        {
            string _category = category;
            IEnumerable<Knife> knive = null;
            string currCategory = "";
            if (string.IsNullOrEmpty(category))
            {
                knive = _allKnives.allKnives.OrderBy(i => i.id);
            }
            else
            {
                if (string.Equals("balisong", category, StringComparison.OrdinalIgnoreCase))
                {
                    knive = _allKnives.allKnives.Where(i => i.Category.nameCategory.Equals("Балисонг")).OrderBy(i => i.id);
                    currCategory = "Балисонг";
                }
                else if (string.Equals("stylet", category, StringComparison.OrdinalIgnoreCase))
                {
                    knive = _allKnives.allKnives.Where(i => i.Category.nameCategory.Equals("Стилет")).OrderBy(i => i.id);
                    currCategory = "Стилет";
                }
                

                
            }
            var kniveObj = new KnifeListViewModel
            {
                GetKnives = knive,
                currCategory = currCategory

            };


            ViewBag.Title = "Страница для юного экстримиста";
            
            return View(kniveObj);
        }
    }
}

Shop/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Date.Interfaces;
using Shop.Date.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class OrderController : Controller
    {
        private readonly IAllOrders allOrders;
        private readonly ShopCart shopCart;

        public OrderController(IAllOrders allOrders, ShopCart shopCart)
        {
            this.allOrders = allOrders;
            this.shopCart = shopCart;
        }

        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Order order)
        {
            shopCart.ListShopItems = shopCart.getShopItems();

            
            if (ModelState.IsValid)
            {
                allOrders.createOrder(order);
                return RedirectToAction("Complete");
            }

            return View(order);
        }

        public IActionResult Complete()
        {
            ViewBag.Massage ="Заказ успешно обработан, наш админестратор свяжется с вами";
            return View();
        }

    }
}

Shop/Controllers/ShopCartController.cs
using Microsoft.AspNetCore.Mvc;
using Shop.Date.Interfaces;
using Shop.Date.Models;
using Shop.Date.Repository;
using Shop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Shop.Controllers
{
    public class ShopCartController: Controller
    {
        private readonly IAllKnives _knifeRep;
        private readonly ShopCart _shopCart;

        public ShopCartController (IAllKnives knifeRep, ShopCart shopCart)
        {
            _knifeRep = knifeRep;
            _shopCart = shopCart;
        }

        public ViewResult Index()
        {
            var items = _shopCart.getShopItems();
            _shopCart.ListShopItems = items;

            var obj = new ShopCartViewModel
            {
                shopCart = _shopCart
            };

            return View(obj);
        }

        public RedirectToActionResult addToCart(int id)
        {
            var item = _knifeRep.allKnives.FirstOrDefault(i => i.id == id);
            if(item != null)
            {
                _shopCart.AddToCart(item);
            }

            return RedirectToAction("Index");
        }
    }
}

Shop/Views/Home/Index.cshtml
@model HomeViewModel

<h2>Самые покупаемые ножи</h2>
<div class="row mt-5 mb-2">
    @{
        foreach (Knife knife in Model.favKnives)
        {
            @Html.Partial("AllKnives", knife)

        }
    }
</div>

Shop/Views/Knives/List.cshtml
<h2>Все НОЖИ</h2>
<h3>@Model.currCategory</h3>
<div class="row mt-5 mb-2">
    @{
        foreach (Knife knife in Model.GetKnives)
        {
            @Html.Partial("AllKnives", knife)

        }
    }
</div>

Shop/Views/Order/Checkout.cshtml
@model Order;

<div class="row">
    <h3>Оформление заказа</h3>
    <form asp-action="Checkout" method="post" class="form-horizontal">
        <div class="frm-group">
            <label asp-for="name"></label>
            <div class="col-md-5">
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
        </div>
        <div class="frm-group">
            <label asp-for="surename"></label>
            <div class="col-md-5">
                <input asp-for="surename" class="form-control" />
                <span asp-validation-for="surename" class="text-danger"></span>
            </div>
        </div>
        <div class="frm-group">
            <label asp-for="adress"></label>
            <div class="col-md-5">
                <input asp-for="adress" class="form-control" />
                <span asp-validation-for="adress" class="text-danger"></span>
            </div>
        </div>
        <div class="frm-group">
            <label asp-for="phone"></label>
            <div class="col-md-5">
                <input asp-for="phone" class="form-control" />
                <span asp-validation-for="phone" class="text-danger"></span>
            </div>
        </div>
        <div class="frm-group">
            <label asp-for="email"></label>
            <div class="col-md-5">
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success", type="submit" value="ЗАВЕРШИТЬ ЗАКАЗ"/>
    </form>

</div>

Shop/Views/Order/Complete.cshtml
<h3>Заказ успешно оформлен</h3>

Shop/Views/Shared/AllKnives.cshtml
@model Knife

<style>
    .btn-warning {
        background: navy; /* Синий цвет фона */
        color: white; /* Белые буквы */
        font-size: 9pt; /* Размер шрифта в пунктах */
    }
</style>

<div class="col-lg-4">
    <img class="img-thumnail" src="@Model.imgKnife" width="250" height="250" alt="@Model.nameKnife" />
    <h2>@Model.nameKnife</h2>
    <p>@Model.shortDisc</p>
    <p>Цена: @Model.priceKnife.ToString("c")</p>
    <p><a class="btn btn-warning" asp-controller="ShopCart" asp-action="addToCart", asp-route-id="@Model.id">Добавить в корзину</a></p>

</div>

Shop/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">_a.r.g.u.m.e.n.t_</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link" href="/">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Knive/List">Режики</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Knive/List/balisong">Балисонги</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/Knive/List/stylet">Стилеты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="/ShopCart/">Корзина</a>
                        </li>
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Поиск</button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        @RenderBody()
    </div>
    <footer class="container">
        <p class="float-end"><a href="#">Back to top</a></p>
        <p>© 2021 Шморгуненко Иван · <a href="#">Курсовая работа</a> </p>
    </footer>
    <script src="~/js/bootstrap.min.js"></script>
</body>
</html>

Shop/Views/ShopCart/Index.cshtml
@model ShopCartViewModel

<div>
    @foreach(var el in Model.shopCart.ListShopItems){
    <div class="alert alert-warning mt-3">
        <b>Нож:</b> @el.knife.nameKnife<br />
        <b>Цена:</b>@el.knife.priceKnife.ToString("c")

    </div>

    }
    <hr />
    <a class="btn btn-danger" asp-controller="Order" asp-action="Checkout">Оплатить</a>

</div>